### PR TITLE
Raised Compatibility Update

### PR DESCRIPTION
**Pull request by Obscure2020**
The Raised mod has changed where it looks for the file `hotbar_selection.png`. It now provides its own internal copy at `assets/raised/textures/gui/sprites/hud/hotbar_selection.png`, and also will only apply replacement textures if they are specified at that location.

The recent changes to GUI structuring within the newest resource pack formats have cut off `hotbar_selection.png` so that it is no longer a square, and VanillaXBR does already correctly reflect this. This PR would restore compatibility with Raised by adding an additional version that **_IS_** a square, in the location that Raised is looking.

I have tested this change on my computer with the latest release of Raised, and I can confirm it works.

### CODE REVIEW

**Comment by mistrk7** [comment]
Hm, okay. does it really work like that?

**Comment by Obscure2020** [comment]
Uhhhh... _yes?_ I told you I tested this. Without providing an actually-square version of the texture at this specific path inside the resource pack, Raised will default to using its own internal 24x24 version of the texture.

Here, look at this. This is with Raised, and with VanillaXBR active, but without this PR added:



It took me a while to notice what was wrong, but a few days ago, while taking some screenshots in a Hypixel SMP that my siblings set up, I noticed that my hotbar selector looked too angular. Sure enough, the VanillaXBR texture was _**NOT**_ being used, so I researched why.

Here is how Raised appears, with VanillaXBR active, and _with_ this PR added:

**Comment by mistrk7** [comment]
Nuh uh

**Comment by mistrk7** [comment]
Alright it's merged. ty. Next time please name your commits better (they are bad). I will elaborate on discord

**Pull request merged**
