### PR TITLE
New and Improved Squoosh

### PR DESCRIPTION
**Pull request by Obscure2020**
Now that I've finally gotten SquooshPNG back up and running, I've run it over the whole `main` branch again to apply some new optimizations and catch up on all the new/changed textures that I missed. This should come out to a little over 1.5 MB saved.

### CODE REVIEW

**Comment by Obscure2020** [comment]
Contributions from @rhysdh540 have now been merged into this PR.

**Comment by rhysdh540** [comment]
oh im not done yet...

**Comment by Obscure2020** [comment]
Yes, but are you done enough for now for @mistrk7 to merge this?

**Comment by rhysdh540** [comment]
Ok fine yes for now

**Comment by mistrk7** [comment]
Is it really done

**Comment by Obscure2020** [comment]
For the time being, yeah. We ran it through the latest versions of our tools after working out some kinks and improving their results. We're not gonna have more to contribute until we (slowly, maybe) find ways to improve our tools even further.

**Comment by rhysdh540** [comment]
yeah what he said

**Comment by mistrk7** [comment]
Alright, thanks guys. I know how passionate you are about crunching. 

I am not sure if I will let in any more of these from now on though since in all honestly I think they're pretty redundant. However I still appreciate the contributions.

**Comment by Obscure2020** [comment]
> I am not sure if I will let in any more of these from now on though since in all honestly I think they're pretty redundant.

They become less redundant the more un-optimized textures are added. We'll likely wait a few updates of the pack before giving everything a once-over again. There's always a chance that small incremental improvements to our tools will be able to shave one or two more bytes off of older textures, but the more significant contribution will be the optimization of new textures, added by you (or others), that _haven't_ been optimized before.

So if we wait for a few more updates to the pack to go by, a larger proportion of the pack will be new textures, and the benefit of a new crunch pass will be more pronounced.

**Pull request merged**
