### PR TITLE
Optimize All PNGs

### PR DESCRIPTION
**Pull request by Obscure2020**
Ran through two passes of Squoosh, one pass of Crunch (which I had agreed with @CodeF53 I would do), and then one more pass of Squoosh. I did not think the last two passes would do anything, but I was wrong. Work shall proceed in future to figure out how to improve Squoosh and ensure the best results with only one pass of Squoosh.

By the way, if you merge this in, I do recommend that you use the "squash" or "merge as a single commit" option, so that these four commits go into VanillaXBR as a single commit. Keeps your commit logs a little cleaner. 😉

### CODE REVIEW

**Comment by Obscure2020** [comment]
Wait, hold on. New development. @rhysdh540 forked *my* fork, and he may actually have something to contribute too. I'm gonna open a new PR after I get changes back from him. Hold tight!

**Comment by rhysdh540** [comment]
Isn’t “mark as draft” a thing?

**Comment by Obscure2020** [comment]
I don't know. Oy. I have not opened many pull requests before. Just work on yours, man. I'm excited to see what changes.

**Comment by mistrk7** [comment]
I like this, buut the problem is VxBR is obviously an active project and I don't know if it's exactly a good idea to run optimisers over textures i'm actively working on.

I'll look at it on desktop. But perhaps this should be a final pass sort of thing before release?

**Pull request closed without merging**
